### ISSUE TITLE
Crash on Startup in dev environment

### ISSUE THREAD

**Issue by Domochevsky** [MineMaarten/IGW-mod#20]
Hey. With "IGW-Mod-1.7.10-1.1.1-17-universal.jar" thrown into the mods folder in my eclipse dev environment it crashes on startup with two errors.

The first one is likely not much of an issue (I'll make a separate ticket for it.), but the second one actually crashes.

http://pastebin.com/5UYHNEqP  <- the crash log

Is this an issue due to lack of obfuscation in the dev environment? I have not encountered this before.

**Comment by MineMaarten** [comment]
Just to make sure: You are in a 1.7.10 environment right? If no, that's the issue.
If yes, then indeed, I can only think of the dev environment not being properly deobfuscated.

**Comment by Domochevsky** [comment]
I am indeed in a 1.7.10 environment, yes. But why would it not properly deobfuscate that particular field? What is that even? It seems like your mod is actively trying to grab an obfuscated field and can't find it. (Likely because it isn't obfuscated.)

This is somewhat mysterious.

**Comment by TheJulianJES** [comment]
Try the IGW deobf version.

**Comment by MineMaarten** [comment]
Ah, good point. If you don't have CodeChickenCore (or any other deobfuscating mod) in your environment, you need to grab the deobfuscated version of IGW indeed. Tnx Julian for pointing it out.

**Comment by Domochevsky** [comment]
Hm... right, so do I just grab the master here and insert it into my dev environment, work with it, and THEN, after I've build everything and handed it to regular Minecraft, use the regular IGW instead?

**Comment by MineMaarten** [comment]
Possible. But there is also a maven for the deobfuscated version (look at the PneumaticCraft build.gradle to see an example on how it's done).

**Comment by MineMaarten** [comment]
I assume everything is fine now :)
