### ISSUE TITLE
Feature Request: Dynamically create pages .txt files

### ISSUE THREAD

**Issue by KJA1582** [MineMaarten/IGW-mod#21]
@MineMaarten Is there any way to dynamically create the files IGW loads at runtime or do they have to be present already?

**Comment by MineMaarten** [comment]
Answered on the https://github.com/MightyPirates/OpenComputers/issues/599#issuecomment-90531930 instead :P

**Comment by KJA1582** [comment]
Just to get this side up-to-date, yes a hook as discussed in  https://github.com/MightyPirates/OpenComputers/issues/599#issuecomment-90531930
is perfect.
