### ISSUE TITLE
IGW Crash on Startup (in modpack)

### ISSUE THREAD

**Issue by Xiaminou** [MineMaarten/IGW-mod#28]
IGW: 1.1.3-18
Forge: 1403
Pastebin: http://pastebin.com/yNVAYD1L

**Comment by sandalle** [comment]
Dupe of #26 ?

**Comment by Xiaminou** [comment]
Maybe, then how do I fix it? it's been 2 weeks, has there been any new version of IGW to fix the bugs?

**Comment by sandalle** [comment]
I disabled the IGW-Mod support in the only mod using it for [Modderation: Permabanned](http://www.technicpack.net/modpack/details/modderation-permabanned-edition.449941), Extra Cells 2, and then removed the IGW-Mod jar from client and server (server is optional anyways) during my testing.

**Comment by Xiaminou** [comment]
Well yeah, right now I'm playing without it, but I need it for Pneumaticraft.

**Comment by MineMaarten** [comment]
I'm very sorry for the delay people :|
