### ISSUE TITLE
modid subfolder derp?

### ISSUE THREAD

**Issue by Keridos** [MineMaarten/IGW-mod#31]
My IGWMod is telling me its looking at "modid/assets/wiki", but it should rather look at "assets/modid/wiki" per default. Using version 1.1.4-20.

Update: this seems to be displayed wrong only. But additionally the intro and for servers pages are not working anymore, since they need to be located in the same subfolder. That needs to be fixed imo.

**Comment by MineMaarten** [comment]
Fixed, the one about server and intro pages have been moved to assets/igwmod from assets/minecraft.
