### ISSUE TITLE
Rotary Craft + IGWMod crash

### ISSUE THREAD

**Issue by SilverScreamBr** [MineMaarten/IGW-mod#35]
http://paste.ee/p/U9DYJ

**Comment by Leadcraft** [comment]
Same here. If you leave out IGW, Pneumaticcraft works with RC just fine.

Tried it with both 1.1.4-20 and 1.1.2-19.

http://pastebin.com/02yhTsFu

**Comment by ReikaKalseki** [comment]
Also fixed from my end, but a good idea to leave this in for future cases.
