### ISSUE TITLE
Cannot tell what version got installed when installing mod with igw

### ISSUE THREAD

**Issue by TheQuadShot** [MineMaarten/IGW-mod#41]
in my test environment, I only run what is available through Curse as a "release" or "beta", no dev code/mod's. I installed phumaticcraft which I believe is the mod that pulled in the igw, when I look in the directory for a version number the file name is IGW-Mod.jar, I was looking for a version number to put into bug reports since I feel that is important information needed by the "dev" team.

**Comment by MineMaarten** [comment]
At the time I spent a lot of time trying to get this working, with no result. However, I just thought of ways to do it :).
