### ISSUE TITLE
When switching between mod's igw only shows last page seen if page has same name

### ISSUE THREAD

**Issue by TheQuadShot** [MineMaarten/IGW-mod#42]
for instance, I look at PnumaticCraft baseConcepts, then look at HydrauliCraft baseConcepts, when I click on the tab for PnumaticCraft then click on baseconcepts page, the HydrauliCraft page is displayed. I can get back to the PnumaticCraft baseconcepts page after clicking pages from PnumaticCraft that are below the first grouping of pages, but If I click on Hydraulicraft pages, then switch the tab to PnumatiCraft and click baseconcepts I get the Hydraulicraft page. hope that makes sense. 

The more I look at this the more I am thinking it's a PnumaticCraft or Hydraulicraft bug, I'll let you decide, let me know if you want it moved over there (very high probability I'm doing something wrong). I noticed when looking at the source, your basicconcepts page has [prefix{1}]Basic Materials[prefix{}] at the top, but in Hydraulicraft, I don't have that, or anything else, just links to other pages.

**Comment by MineMaarten** [comment]
This is an IGW bug. I haven't worked out proper distinguishing between mods yet. I'll fix it with HydrauliCraft with the new pages to test when it's out.

**Comment by Keridos** [comment]
Is this the cause that causes the entire IGWmod to try to load pages from different location?
When I press "I" on a block of my own mod all pages regarding my block work fine. But when I press I on another block it tries to find my pages in that mods subfolder instead of my mods subfolder in assets.

**Comment by MineMaarten** [comment]
In the current IGW version it's a convention to prefix page names with your modid, so if I want to access my menu/baseConcepts page, I do "pneumaticcraft:menu/baseConcepts". I've expanded this in upcoming version to also work for item/block pages to preserve consistency. Also if you don't prefix it (although I highly recommend doing so), it tries to find the owner by looking at the mod owner of the itemstack of the tab that's currently open.
