### ISSUE TITLE
On focus/hover pop-up tool tip show's default IGW Key, Not current mapped key

### ISSUE THREAD

**Issue by TheQuadShot** [MineMaarten/IGW-mod#44]
I have my IGW key mapped to another key, (i is inventory for me) and when I focus/look on/at a block, after a few seconds there is a pop-up type of text telling me there is an IGW page for it and to hit "i" to open IGW. Hope that make sense.

**Comment by MineMaarten** [comment]
Ah ok, the showing instructions aren't mapped properly to the selected keybinding.
