### ISSUE TITLE
ingame error messages need to wrap if they exceed the page width

### ISSUE THREAD

**Issue by TheQuadShot** [MineMaarten/IGW-mod#45]
I'm in my dev env (so I trust maven to keep me current) and I'm looking at my wiki pages and the error message of where IGW is looking for a file is too long and I can't read it. it's kind of hard to see in this screen shot

![2015-07-21_04 07 16](https://cloud.githubusercontent.com/assets/11265900/8799392/98a5161e-2f5e-11e5-853b-2df92187d0a7.png)

**Comment by MineMaarten** [comment]
Yeah, the problem is that it doesn't wrap a very long word currently (like a link).
