### ISSUE TITLE
Random Crash NPE

### ISSUE THREAD

**Issue by ruifung** [MineMaarten/IGW-mod#49]
Here's a random crash that I can't seem to reproduce - It just crashed randomly (so far, once - when I tried to sleep.)

http://openeye.openmods.info/crashes/4f9f8ff4892db762ec32793fd44dbd65

**Comment by ruifung** [comment]
uh, this crashes when i never pressed I at all.

**Comment by MineMaarten** [comment]
Well, I could reliably reproduce the same crash by doing as I explained in the commit message. Additionally, even though you don't say you pressed 'i', your crashlog shows it originates from pressing a keybind. Weird.

**Comment by ruifung** [comment]
Yeah, I know right. If its fixed, then its fixed. Meh.
