### ISSUE TITLE
No Info Available about this topic

### ISSUE THREAD

**Issue by BeardlessBrady** [MineMaarten/IGW-mod#60]
So well going into the in game wiki, no pages show up. It just says the message "No info available about this topic. IGW-Mod is currently looking for ..." I go check the location it specifies and I am able to find the file uncorrupted and should be working perfectly.

**Comment by MineMaarten** [comment]
Could you provide more info? The path IGW claims to look at (which presumably is the exact same path as the file is in)?

**Comment by 1skandar** [comment]
I can confirm this. The mods all show up and all the topics show up, but clicking on any of them just shows the "No info available" and the location. I've checked and double checked the location it gives and it appears to be 100% correct. And the previous version works correctly.

**Comment by 1skandar** [comment]
Oh, and this works for all mods I have tested it against, Hydraulicraft, Pneumaticraft, OpenModularTurrets, and ExtraCells.

**Comment by MineMaarten** [comment]
Hmm updated IGW-Mod? it 'recently' has gotten an update where names needed to be prefixed with the modid. This is a long time ago where I transitioned into this, so... maybe you're running a too old IGW-Mod?

**Comment by spamenigma** [comment]
Same issue here, using version IGW-Mod-1.7.10-1.1.10-30-universal

Thanks

**Comment by 1skandar** [comment]
Double checked, everything works in 29, everything fails to work in 30. The paths it displays when it give you the "No info available" error are correct, as far as I can tell.

**Comment by MineMaarten** [comment]
Hmm couldn't reproduce it in my dev environment. I could outside the dev environment though.. I'll look into it.

**Comment by MineMaarten** [comment]
Ok figured out what I did wrong by looking at the commits of last version. Got to love git :). Also thanks @1skandar  for the version info, it helped to be able to narrow it down :). Version up in a few minutes.
