### ISSUE TITLE
[1.8] Mod incompatibilty with Shatter

### ISSUE THREAD

**Issue by TheSilkMiner** [MineMaarten/IGW-mod#63]
When both Shatter and IGW Mod are installed, the client crashes when trying to open IGW's gui.

### How to replicate the crash
1. Install both [Shatter (currently using version 5.0.0)](http://ichun.us/mods/shatter/) and IGW Mod (version 1.2.0-27)
2. Enter either a singleplayer world or a multiplayer server.
3. Try to open IGW's GUI with `I`.

### Crash report
[On Pastebin](http://pastebin.com/QYxZciz4)

### Probabile causes
- The crash report says it is a NPE [on this line](https://github.com/MineMaarten/IGW-mod/blob/master/src/igwmod/gui/GuiWiki.java#L696). There, only `page` can be `null`. Following back the stacktrace, the call which leads to the crash is `setCurrentFile(wikiEvent.pageOpened, entity);`, where the `null` part is almost surely `pageOpened` of `wikiEvent`. Since `wikiEvent` is assigned previously, following the method calls, we reach [an entry lookup in a `Map`](https://github.com/MineMaarten/IGW-mod/blob/master/src/igwmod/api/WikiRegistry.java#L86). I don't know why or how the result of this call can return `null` with a mod and a valid value without it, though.

### Probabile resolution
As a temporary fix, the following could apply:
```java
public void setCurrentFile(Entity entity) {

        EntityWikiEvent wikiEvent = new EntityWikiEvent(entity);
        wikiEvent.pageOpened = WikiRegistry.getPageForEntityClass(entity.getClass());
       
       // Patch starts
       if (wikiEvent.pageOpened == null) {
            
            // I could not find any logger class.
            System.err.println("No valid page for entity specified.");
            System.err.println("This is a serious error!");
            return;
       }
       // Patch ends
       
        MinecraftForge.EVENT_BUS.post(wikiEvent);
        setCurrentFile(wikiEvent.pageOpened, entity);
    }
```
Anyway I think it would be better if a "real" solution could be found.

### Mod information
| Property | Value |
|----------|-------|
| **Mod name** | Shatter |
| **Author** | iChun |
| Mod ID | Shatter |
| Version | 5.0.0 |
| Mod URL | [http://ichun.us/mods/shatter/](http://ichun.us/mods/shatter/) |

**Comment by MineMaarten** [comment]
Thanks for the detailed report, sorry for responding so late :/..
The nullpointer actually says that either 'page' is null or 'link' is null. Link can't be null for normal wiki tabs, page is more likely to be null. So I'm catching that in the upcoming version.
