### ISSUE TITLE
Weird clientside crash on 1.7.10

### ISSUE THREAD

**Issue by Keridos** [MineMaarten/IGW-mod#64]
http://pastebin.com/MBcWCjFP
Forge 10.13.4.1558
IGWMod 1.1.11-32

Seems to be caused by another mod though, currently searching for the mod that causes this.

**Comment by MineMaarten** [comment]
It helps not to let the pastebin expire...

**Comment by Keridos** [comment]
Derp: https://paste.ee/p/JOz9i
