### ISSUE TITLE
Incompatibility with 1.8.9 version

### ISSUE THREAD

**Issue by blockbreaker1361** [MineMaarten/IGW-mod#66]
When I open IGW, it gives info on the mod, but the crafting recipes in it show broken textures and not actual items. Here are some screenshots of what I mean. I am on the latest version available.
http://imgur.com/a/h2mAf

**Comment by MineMaarten** [comment]
Well, that's to do with the fact that PneumaticCraft itself is Alpha and barely has working textures.
