### ISSUE TITLE
client crash "i" on a cow

### ISSUE THREAD

**Issue by Kropter** [MineMaarten/IGW-mod#67]
i tried some vanilla things, worked, cow crashed client, stopped testing

FTB Unstable 3.0.17

IGW-Mod-1.8.9-1.2.3-3-universal.jar

http://pastebin.com/Np7cH9Ym

**Comment by tahg** [comment]
I've gotten this as well.  It appears that unknown entities don't provide a default file name.  Is that all entities?

**Comment by GirafiStudios** [comment]
From what I can tell this happens with all entities, even PneumaticCrafts own drones which should have a wiki entry.

**Comment by mrgreaper** [comment]
yep can confirm, does it with all entites, i get the same crash

heres one i crashed earlier looking at an elevator from thuts elevator mod and pressing i
http://pastebin.com/hwJhGUQK

**Comment by MineMaarten** [comment]
Ah, forgot to forward port this into the 1.8.8 version. https://github.com/MineMaarten/IGW-mod/issues/49
