### ISSUE TITLE
GUI related crash when inspecting a player on a server [1.8.9]

### ISSUE THREAD

**Issue by VoilaTada** [MineMaarten/IGW-mod#69]
Viewing a player and pressing the IGW key crashes the client.

[crash-2016-02-14_14.01.23-client.txt](https://github.com/MineMaarten/IGW-mod/files/129861/crash-2016-02-14_14.01.23-client.txt)

**Comment by VoilaTada** [comment]
Forge Log.
[fml-client-3.txt](https://github.com/MineMaarten/IGW-mod/files/129862/fml-client-3.txt)

**Comment by MineMaarten** [comment]
Duplicate with #67
