### ISSUE TITLE
[1.7.10] Crash

### ISSUE THREAD

**Issue by tanto259** [MineMaarten/IGW-mod#73]
Minecraft crash when exploring the in-game wiki of Extra Cell 2 mod.
Crash report: [http://pastebin.com/GrNtCXMP](http://pastebin.com/GrNtCXMP)

**Comment by V55V551N** [comment]
I have the same issue when scrolling down the blocks and items list:

http://pastebin.com/DZazkxGG

**Comment by tanto259** [comment]
No longer reduplicatable for me
