### ISSUE TITLE
Disable Option

### ISSUE THREAD

**Issue by HendrikLober** [MineMaarten/IGW-mod#74]
Please NEVER display an annoying and redundant informational text directly in the center of the screen. This violates every principle of user interaction design.
Is there a way to turn these constant notifications off? This is making modpacks which include the IGW mod unplayable for me.
If there is no such configuration option please add it immediately.

**Comment by MineMaarten** [comment]
How about looking in the config BEFORE posting here?

**Comment by HendrikLober** [comment]
The current Skyfactory Modpack has no such configuration option, that's why I'm writing in the first place. I assumed there's a second config file or the like with such an option which I missed, but there seems to be none.

Options in the config file:
general {
    B:"Automatically scale to GUI scale AUTO in IGW GUI"=true
    B:"Debug mode"=false
    B:"Pop-up every time"=false
    S:"Pop-up page"=
    B:"Should show tooltip"=false

    # When enabled, this will notify players when IGW-Mod is not installed even though mods add support.
    B:enable_missing_notification=false
}
