### ISSUE TITLE
Crash: java.lang.NullPointerException: Rendering screen

### ISSUE THREAD

**Issue by Xiaminou** [MineMaarten/IGW-mod#89]
Crashed when I clicked on blocks after opening the IGW interface.
Crash Report: [crash-2017-11-19_16.01.46-client.txt](https://github.com/MineMaarten/IGW-mod/files/1485650/crash-2017-11-19_16.01.46-client.txt)

And this one is when I clicked on a drone in the IGW interface while browsing pneumaticcraft's part. This one was made in an instance with just PNC:R and IGW.
Crash Report: [crash-2017-11-19_16.18.35-client.txt](https://github.com/MineMaarten/IGW-mod/files/1485667/crash-2017-11-19_16.18.35-client.txt)

Minecraft: 1.12.2
Forge: 2544
Mods: [list.txt](https://github.com/MineMaarten/IGW-mod/files/1485652/list.txt)

**Comment by xKnightGamingx** [comment]
I just got this error aswell

**Comment by MineMaarten** [comment]
Thanks for the report, a new version will be up on Curse shortly.
