### ISSUE TITLE
External links don't work for pages without "www" in the URL

### ISSUE THREAD

**Issue by desht** [MineMaarten/IGW-mod#90]
Tried a link like this:
```
[link{https://crafttweaker.readthedocs.io/en/latest/#Mods/PneumaticCraft_Repressurized/PneumaticCraft_Repressurized}]CraftTweaker support[link{}]
```
... but it didn't work.

Checking the IGW code, looks like it will only work for URL's containing "www" - see https://github.com/MineMaarten/IGW-mod/blob/master/src/igwmod/gui/LocatedString.java#L80

**Comment by cam72cam** [comment]
This can be worked around by putting #www at the end of the url.  It's a crappy hack but it works

**Comment by cam72cam** [comment]
Thanks @MineMaarten
