### ISSUE TITLE
1.7.10 - Item HUD 

### ISSUE THREAD

**Issue by HaniXP** [MineMaarten/IGW-mod#92]
Hi there,

is there any way to prevent item names from showing up on the top right side of the HUD?

like here for example : https://imgur.com/a/FA2frLX

I also want to prevent it from giving  "Press I to check etc" pop ups when looking at a certain block cuz its a bit bothering me xD.. I looked at the config file but i dont see any appropriate options to disable these 2 things..

solutions & answers are highly appreciated.

**Comment by MaartenKok8** [comment]
The name in the top right isn't added by IGW..
Also, there ís a config option for the press I thing (titled 'Should show tooltip'), and it should automatically get disabled as soon as you open the IGW GUI once.
